"""add driver to rides

Revision ID: 76767bca2471
Revises: 9fd8448449bc
Create Date: 2026-08-31 06:51:34.361818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76767bca2471'
down_revision = '9fd8448449bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'drivers', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
