"""add driver stage

Revision ID: 809fe2b628df
Revises: ee2b8022bf1d
Create Date: 2026-09-22 21:33:38.263936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809fe2b628df'
down_revision = 'ee2b8022bf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stage_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stage_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('stage_longitude')
        batch_op.drop_column('stage_latitude')
        batch_op.drop_column('stage_name')

    # ### end Alembic commands ###
