"""add ride destination coordinates

Revision ID: c51667e87ec7
Revises: 809fe2b628df
Create Date: 2026-09-23 09:20:26.893410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51667e87ec7'
down_revision = '809fe2b628df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('stage_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('destination_longitude')
        batch_op.drop_column('destination_latitude')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('stage_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
