"""fix passenger spelling

Revision ID: d9edd0cbcda1
Revises: 3979798ebed8
Create Date: 2026-08-23 22:00:56.009179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9edd0cbcda1'
down_revision = '3979798ebed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('rides_passanger_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['passenger_id'], ['id'])
        batch_op.drop_column('passanger_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passanger_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rides_passanger_id_fkey'), 'users', ['passanger_id'], ['id'])
        batch_op.drop_column('passenger_id')

    # ### end Alembic commands ###
