"""add pickup coordinates to rides

Revision ID: ee2b8022bf1d
Revises: 7a7cd204e554
Create Date: 2026-09-01 07:36:33.340396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2b8022bf1d'
down_revision = '7a7cd204e554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('pickup_longitude')
        batch_op.drop_column('pickup_latitude')

    # ### end Alembic commands ###
